# Generated by Django 5.1.1 on 2024-09-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nginxlog',
            old_name='uri',
            new_name='url',
        ),
    ]
